apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sidstringapp-1
  namespace: default
  labels:
    app: sidstringapp-1
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: sidstringapp-1.k8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sidstringapp-1
            port:
              number: 80

